/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Installments } from "./Installments";
import { InstallmentsCountArgs } from "./InstallmentsCountArgs";
import { InstallmentsFindManyArgs } from "./InstallmentsFindManyArgs";
import { InstallmentsFindUniqueArgs } from "./InstallmentsFindUniqueArgs";
import { CreateInstallmentsArgs } from "./CreateInstallmentsArgs";
import { UpdateInstallmentsArgs } from "./UpdateInstallmentsArgs";
import { DeleteInstallmentsArgs } from "./DeleteInstallmentsArgs";
import { InstallmentsService } from "../installments.service";
@graphql.Resolver(() => Installments)
export class InstallmentsResolverBase {
  constructor(protected readonly service: InstallmentsService) {}

  async _installmentsItemsMeta(
    @graphql.Args() args: InstallmentsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Installments])
  async installmentsItems(
    @graphql.Args() args: InstallmentsFindManyArgs
  ): Promise<Installments[]> {
    return this.service.installmentsItems(args);
  }

  @graphql.Query(() => Installments, { nullable: true })
  async installments(
    @graphql.Args() args: InstallmentsFindUniqueArgs
  ): Promise<Installments | null> {
    const result = await this.service.installments(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Installments)
  async createInstallments(
    @graphql.Args() args: CreateInstallmentsArgs
  ): Promise<Installments> {
    return await this.service.createInstallments({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Installments)
  async updateInstallments(
    @graphql.Args() args: UpdateInstallmentsArgs
  ): Promise<Installments | null> {
    try {
      return await this.service.updateInstallments({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Installments)
  async deleteInstallments(
    @graphql.Args() args: DeleteInstallmentsArgs
  ): Promise<Installments | null> {
    try {
      return await this.service.deleteInstallments(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
