/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { InstallmentsService } from "../installments.service";
import { InstallmentsCreateInput } from "./InstallmentsCreateInput";
import { Installments } from "./Installments";
import { InstallmentsFindManyArgs } from "./InstallmentsFindManyArgs";
import { InstallmentsWhereUniqueInput } from "./InstallmentsWhereUniqueInput";
import { InstallmentsUpdateInput } from "./InstallmentsUpdateInput";

export class InstallmentsControllerBase {
  constructor(protected readonly service: InstallmentsService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Installments })
  async createInstallments(
    @common.Body() data: InstallmentsCreateInput
  ): Promise<Installments> {
    return await this.service.createInstallments({
      data: data,
      select: {
        id: true,
        paymentNumber: true,
        totalAmount: true,
        totalPayments: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Installments] })
  @ApiNestedQuery(InstallmentsFindManyArgs)
  async installmentsItems(
    @common.Req() request: Request
  ): Promise<Installments[]> {
    const args = plainToClass(InstallmentsFindManyArgs, request.query);
    return this.service.installmentsItems({
      ...args,
      select: {
        id: true,
        paymentNumber: true,
        totalAmount: true,
        totalPayments: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Installments })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async installments(
    @common.Param() params: InstallmentsWhereUniqueInput
  ): Promise<Installments | null> {
    const result = await this.service.installments({
      where: params,
      select: {
        id: true,
        paymentNumber: true,
        totalAmount: true,
        totalPayments: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Installments })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateInstallments(
    @common.Param() params: InstallmentsWhereUniqueInput,
    @common.Body() data: InstallmentsUpdateInput
  ): Promise<Installments | null> {
    try {
      return await this.service.updateInstallments({
        where: params,
        data: data,
        select: {
          id: true,
          paymentNumber: true,
          totalAmount: true,
          totalPayments: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Installments })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteInstallments(
    @common.Param() params: InstallmentsWhereUniqueInput
  ): Promise<Installments | null> {
    try {
      return await this.service.deleteInstallments({
        where: params,
        select: {
          id: true,
          paymentNumber: true,
          totalAmount: true,
          totalPayments: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
