/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Installments as PrismaInstallments } from "@prisma/client";

export class InstallmentsServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.InstallmentsCountArgs, "select">
  ): Promise<number> {
    return this.prisma.installments.count(args);
  }

  async installmentsItems(
    args: Prisma.InstallmentsFindManyArgs
  ): Promise<PrismaInstallments[]> {
    return this.prisma.installments.findMany(args);
  }
  async installments(
    args: Prisma.InstallmentsFindUniqueArgs
  ): Promise<PrismaInstallments | null> {
    return this.prisma.installments.findUnique(args);
  }
  async createInstallments(
    args: Prisma.InstallmentsCreateArgs
  ): Promise<PrismaInstallments> {
    return this.prisma.installments.create(args);
  }
  async updateInstallments(
    args: Prisma.InstallmentsUpdateArgs
  ): Promise<PrismaInstallments> {
    return this.prisma.installments.update(args);
  }
  async deleteInstallments(
    args: Prisma.InstallmentsDeleteArgs
  ): Promise<PrismaInstallments> {
    return this.prisma.installments.delete(args);
  }
}
